; Default Xbox boot theme. Same keys as BootAnimRXDK bootanim.ini.
cameraMode = 1

PlasmaRender = true
Plasma1 = 0x00ff00
Plasma2 = 0x9fff66
Plasma3 = 0xa0ff60

ShieldRender = true
ShieldWireframe = false
Shield = 0x66ff4d

BlobRender = true
BlobWireframe = false
BlobColor = 0x40ff26
BlobGlow = 0xa0ff40

SceneRender = true
SceneWireframe = false
SceneIntensity = 2
SceneAmbient = 0x35ff1a
SceneDiffuse = 0x35ff1a
SceneSpecular = 0x35ff1a

SlashBackgroundStart = 0x000000
SlashBackgroundEnd = 0xffffff
SlashLipGradientStart = 0x000100
SlashLipGradientEnd = 0x4b9b4b
SlashInnerStage1Gradient1 = 0xd0ff97
SlashInnerStage1Gradient2 = 0xd0ff97
SlashInnerStage1Gradient3 = 0xd0ff87
SlashInnerStage1Gradient4 = 0xd0ff87
SlashInnerStage2Gradient1 = 0xd0ff87
SlashInnerStage2Gradient2 = 0xd0ff87
SlashInnerStage2Gradient3 = 0xcbdf01
SlashInnerStage2Gradient4 = 0x216a17

TradeMarkRender = true
TradeMark = 0x6fbb1b
XboxRender = true
Xbox = 0x62ca13
BrandRender = true
Brand = 0xffffff
